config/routes.rb
Taskmanager::Application.routes.draw do
  root :to => 'sites#index'

  resources :projects do
    resources :tasks, only: :index
  end
  post 'tasks/:task_id/finish', to: 'tasks#finish', as: :finish_task
  post 'tasks/:task_id/take', to: 'tasks#take', as: :take_task
  post 'tasks/:task_id/rollback', to: 'tasks#rollback', as: :rollback_task
  post 'tasks/:task_id/checked', to: 'tasks#checked', as: :checked_task

  # Back-end
  namespace :admin do
    resources :projects
    resources :users, except: [:destroy, :show]
    resources :tasks, except: [:index]
  end

  # Authentication
  scope constraints: lambda { |r| r.env['warden'].user.nil? } do
    get "login", to: "sessions#new", as: :login
  end
  delete "logout", to: "sessions#destroy", as: :logout
  resources :sessions, only: :create
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :overview, :identifier, :name, :status
  has_many :tasks

  STATUS = [:active, :inactive, :archived]
  as_enum :status, STATUS, :column => "status_cd"

  STATUS.each do |status|
    scope status, where(status_cd: statuses(status))
  end

  validates :name, presence: true
  validates :identifier, uniqueness: true, presence: true

  def to_param
    identifier
  end

  def check_status
    if active?
      update_attributes(status: :inactive) unless tasks.active.present?
    else
      update_attributes(status: :active) if tasks.active.present?
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :subject, :description, :priority, :project, :status, :type, :status_cd, :project_id, :assignee, :assignee_id, :creater, :creater_id, :checker, :checker_id

  belongs_to :project
  belongs_to :assignee, class_name: 'User', foreign_key: "assignee_id"
  belongs_to :checker, class_name: 'User', foreign_key: "checker_id"
  belongs_to :creater, class_name: 'User', foreign_key: "creater_id"

  STATUS = [:todo, :toreview, :done]
  TYPE = [:feature, :bug, :research]
  PRIORITY = [:regular, :high]

  as_enum :status, STATUS
  as_enum :type, TYPE
  as_enum :priority, PRIORITY

  after_save { project.check_status }

  scope :active, where('status_cd IN (?)', [statuses(:todo), statuses(:toreview)])
  STATUS.each do |status|
    scope status, where(status_cd: statuses(status))
  end

  validates_presence_of :subject, :priority_cd, :project_id, :status_cd, :type_cd

  def doing?
    todo? && assignee.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :nickname, :password, :password_confirmation

  validates :email, presence: true, uniqueness: true, format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/ }
  validates :password, presence: true, length: 6..20, on: :create

  has_secure_password
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  inherit_resources
  defaults :route_prefix => 'admin'
  layout 'admin'
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController

  protected
  def resource
    @project ||= end_of_association_chain.find_by_identifier!(params[:id])
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < Admin::ApplicationController
  before_filter :save_return_to, only: [:edit, :new, :destroy]

  def create
    create! do |format|
      unless @task.errors.empty? # failure
        format.html { render action: "new" }
      else
        format.html { redirect_to session.delete(:return_to) }
      end
    end
  end

  def update
    update! do |format|
      unless @task.errors.empty? # failure
        format.html { render action: "edit" }
      else
        format.html { redirect_to session.delete(:return_to) }
      end
    end
  end

  def destroy
    destroy! { session.delete(:return_to) }
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  actions :index, :new, :create, :edit, :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authorize

  def go_to_404
    render file: "#{Rails.root}/public/404.html", status: 404, layout: false
  end

  private
  def authorize
    redirect_to login_url, alert: 'Not authorized. Please login.' if current_user.nil?
  end

  def current_user
    warden.user
  end
  helper_method :current_user

  def warden
    env['warden']
  end

  def save_return_to
    session[:return_to] ||= request.referer
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]

  def new
    flash.now.alert = warden.message if warden.message.present?
  end

  def create
    warden.authenticate!
    redirect_to root_url, notice: "Logged in!"
  end

  def destroy
    warden.logout
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @tasks = Task.active
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :save_return_to, :find_task, only: [:take, :finish, :rollback, :checked]

  def index
    redirect_to project_tasks_path(Task.last.project) and return unless params[:project_id]
    @project = Project.find_by_identifier(params[:project_id])
    go_to_404 and return unless @project
    @tasks = @project.tasks
  end

  def take
    @task.update_attributes(assignee: current_user)
    redirect_to session.delete(:return_to)
  end

  def finish
    @task.update_attributes(status: :toreview, assignee: current_user)
    redirect_to session.delete(:return_to)
  end

  def rollback
    @task.update_attributes(status: :todo, assignee: nil, creater: current_user)
    redirect_to session.delete(:return_to)
  end

  def checked
    @task.update_attributes(status: :done, checker: current_user)
    redirect_to session.delete(:return_to)
  end

  private
  def find_task
    @task = Task.find(params[:task_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= simple_form_for([:admin, @project], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.input :name, :input_html => { :class => "span6" } %>
  <%= f.input :identifier, :input_html => { :class => "span6" } %>
  <%= f.input :status, collection: Project.statuses_for_select, selected: Project.statuses(:active), :input_html => { :class => "span6" } %>
  <%= f.input :overview, as: :text, :input_html => { :class => "span9 wysihtml5" } %>

  <div class="control-group">
    <div class="controls">
      <%= f.button :submit, class: 'btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<ul class="breadcrumb">
  <li><a href=<%= admin_projects_path %>>Projects</a> <span class="divider">/</span></li>
  <li class="active">Edit</li>
</ul>

<%= render 'form' %>

app/views/admin/projects/index.html.erb
<ul class="breadcrumb">
  <li><a href="javascript:void(0);">Projects</a> <span class="divider">/</span></li>
  <li class="active">List</li>
</ul>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Identifier</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.identifier %></td>
        <td><%= project.status %></td>
        <td>
          <%= link_to 'Show', [:admin, project], class: 'btn btn-mini' %>
          <%= link_to 'Edit', edit_admin_project_path(project), class: 'btn btn-mini' %>
          <%= link_to 'Destroy', [:admin, project], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Project', new_admin_project_path, class: 'btn btn-primary' %>

app/views/admin/projects/new.html.erb
<ul class="breadcrumb">
  <li><a href=<%= admin_projects_path %>>Projects</a> <span class="divider">/</span></li>
  <li class="active">New</li>
</ul>

<%= render 'form' %>

app/views/admin/projects/show.html.erb
<ul class="breadcrumb">
  <li><a href=<%= admin_projects_path %>>Projects</a> <span class="divider">/</span></li>
  <li class="active">Show</li>
</ul>

<p id="notice"><%= notice %></p>

<p>
  <h3>Name:</h3>
  <%= @project.name %>
</p>
<hr />

<p>
  <h3>overview:</h3>
  <%= @project.overview.html_safe %>
</p>
<hr />

<p>
  <h3>Identifier:</h3>
  <%= @project.identifier %>
</p>
<hr />

<p>
  <h3>Status cd:</h3>
  <%= @project.status %>
</p>

app/views/admin/tasks/_form.html.erb
<%= simple_form_for([:admin, @task], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.input :type, collection: Task.types_for_select, selected: Task.types(:feature), input_html: { class: "span6" } %>
  <%= f.input :subject, input_html: { class: "span6" } %>
  <%#= f.input :project_id, collection: Project.active, input_html: { class: "span6" } %>
  <%= f.association :project, input_html: { class: "span6" } %>
  <%= f.input :status, collection: Task.statuses_for_select, selected: Task.statuses(:todo), input_html: { class: "span6" } %>
  <%= f.association :assignee, label_method: :nickname, value_method: :id, input_html: { class: "span6" } %>
  <%= f.input :priority, collection: Task.priorities_for_select, selected: Task.priorities(:regular), input_html: { class: "span6" }, hint: "Select high priority will diplay red border in tasks list." %>
  <%= f.input :description, as: :text, input_html: { class: "span9 wysihtml5" } %>

  <% if @task.new_record? %>
    <%= f.input :creater_id, as: :hidden, input_html: { value: current_user.id } %>
  <% end -%>

  <div class="control-group">
    <div class="controls">
      <%= f.button :submit, class: 'btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/tasks/edit.html.erb
<ul class="breadcrumb">
  <li><a href=<%= root_path %>>Tasks</a> <span class="divider">/</span></li>
  <li class="active"><%= "Edit ##{@task.id} #{@task.subject}" %></li>
</ul>

<%= render 'form' %>

app/views/admin/tasks/new.html.erb
<ul class="breadcrumb">
  <li><a href=<%= root_path %>>Tasks</a> <span class="divider">/</span></li>
  <li class="active">New</li>
</ul>

<%= render 'form' %>

app/views/admin/users/_form.html.erb
<%= simple_form_for([:admin, @user], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.input :email, :input_html => { :class => "span6" } %>
  <%= f.input :nickname, :input_html => { :class => "span6" } %>
  <%= f.input :password, :input_html => { :class => "span6" } %>
  <%= f.input :password_confirmation, :input_html => { :class => "span6" } %>

  <div class="control-group">
    <div class="controls">
      <%= f.button :submit, class: 'btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<ul class="breadcrumb">
  <li><a href=<%= admin_users_path %>>Users</a> <span class="divider">/</span></li>
  <li class="active">Edit</li>
</ul>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<ul class="breadcrumb">
  <li><a href="javascript:void(0);">Users</a> <span class="divider">/</span></li>
  <li class="active">List</li>
</ul>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New User', new_admin_user_path, class: 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<ul class="breadcrumb">
  <li><a href=<%= admin_users_path %>>Users</a> <span class="divider">/</span></li>
  <li class="active">New</li>
</ul>

<%= render 'form' %>

app/views/layouts/_admin_sidebar.html.erb
<div class="sidebar-nav">
  <ul class="nav nav-stacked left-menu">
    <li class=<%= "active" if params[:controller] == 'admin/users' && params[:action] == 'edit' %>>
      <a href=<%= edit_admin_user_path(current_user) %>>
        <span class="box">
          <i class="radmin-icon radmin-user-2"></i>
        </span>
        <span class="hidden-tablet hidden-phone">Account</span>
      </a>
    </li>
    <li class=<%= "active" if params[:controller] == 'admin/users' && params[:action] != 'edit' %>>
      <a href=<%= admin_users_path %>>
        <span class="box">
          <i class="radmin-icon radmin-user"></i>
        </span>
        <span class="hidden-tablet hidden-phone">Users</span>
      </a>
    </li>
    <li class=<%= "active" if params[:controller] == 'admin/projects' %>>
      <a href=<%= admin_projects_path %>>
        <span class="box">
          <i class="radmin-icon radmin-book"></i>
        </span>
        <span class="hidden-tablet hidden-phone">Projects</span>
      </a>
    </li>
    <li class=<%= "active" if params[:controller] == 'admin/tasks' %>>
      <a href=<%= new_admin_task_path %>>
        <span class="box">
          <i class="radmin-icon radmin-pencil"></i>
        </span>
        <span class="hidden-tablet hidden-phone">Tasks</span>
      </a>
    </li>
  </ul>
</div>

app/views/layouts/_alert.html.erb
<% if flash.present? %>
  <div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <% flash.each do |name, msg| %>
      <strong><%= name.capitalize %>!</strong> <%= msg %>
    <% end %>
  </div>
<% end -%>

app/views/layouts/_navigation.html.erb
<div class="row-fluid hidden-phone hidden-tablet" style="padding-top:20px;">
  <div class="span12 top-stats">
    <ul class="top-nav-boxes">
      <li class="top-stats-arrow" title="Hide Top Stats" id="hide-top-stats">
      <img src="/assets/chevron-left.png" alt="Hide Top Stats"/>
      </li>
      <li class="first">
      <a href="#">
        <i class="radmin-pencil"></i>
        <span>New Task</span>
      </a>
      </li>
      <li>
      <a href="#">
        <i class="radmin-pencil-2"></i>
        <span>New Project</span>
      </a>
      </li>
      <li>
      <div class="notifications-wrapper">
        <div class="notifications">
          <strong>3</strong>
        </div>
      </div>
      <a href="#">
        <i class="radmin-folder-2"></i>
        <span>New Task Folder</span>
      </a>
      </li>
      <li id="color-switcher-control">
      <a href="#">
        <i class="radmin-cog"></i>
        <span>Journal</span>
      </a>
      </li>
      <li>
      <div class="notifications-wrapper">
        <div class="notifications">
          <strong>12</strong>
        </div>
      </div>
      <a href="#">
        <i class="radmin-user-3"></i>
        <span>Team Members</span>
      </a>
      </li>
      <li>
      <a href="#">
        <i class="radmin-cabinet"></i>
        <span>History</span>
      </a>
      </li>
      <li>
      <a href="#">
        <i class="radmin-file-2"></i>
        <span>Wiki</span>
      </a>
      </li>
      <li>
      <a href="#">
        <i class="radmin-newspaper"></i>
        <span>Mockups</span>
      </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner black-gradient">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="/"><span class="rad">Task</span>manager</a>
      <% if current_user %>
        <div class="nav-collapse collapse">
          <p class="navbar-text pull-right">
            <a id="user-popover" href=<%= edit_admin_user_path(current_user) %> class="navbar-link user-info"> <i class="radmin-icon radmin-user"></i><%= current_user.nickname %></a>
            <a href=<%= new_admin_task_path %> class="btn btn-mini btn-inverse navbar-link new-task"> <i class="radmin-icon radmin-cube"></i>New Task</a>
            <a href=<%= logout_path %> data-method="delete" class="btn btn-mini btn-inverse navbar-link logout"> <i class="radmin-icon radmin-redo"></i>Logout</a>
          </p>

          <%#<form class="navbar-search pull-right">%>
            <%#<input type="text" class="span2 search-query" placeholder="Search">%>
          <%#</form>%>
        </div>
      <% end -%>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AnderLabs | Taskmanager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!--[if lte IE 9]>
    <script src="assets/placeholder.js"></script>
    <![endif]-->
    <!--[if lte IE 7]>
    <script src="lte-ie7"></script>
    <![endif]-->

    <!--[if (lt IE 9) & (!IEMobile)]>
      <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/topbar' %>
    <%#= render 'layouts/navigation' %>

    <div class="container-fluid main-container">
      <div class="row-fluid">
        <div class="span12">
          <%= render 'layouts/admin_sidebar' %>

          <div class="container-fluid content-wrapper">
            <div class="row-fluid">
              <div class="span12">
                <% flash.each do |name, msg| %>
                  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                    <a class="close" data-dismiss="alert">×</a>
                    <%= msg %>
                  </div>
                <% end %>
                <%= yield %>
              </div>
            </div>
          </div>

          <div class="row-fluid">
            <div class="span12">&nbsp;</div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AnderLabs | Taskmanager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

    <!--[if lte IE 9]>
    <script src="assets/placeholder.js"></script>
    <![endif]-->
    <!--[if lte IE 7]>
    <script src="lte-ie7"></script>
    <![endif]-->

    <!--[if (lt IE 9) & (!IEMobile)]>
    <script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
  </head>

  <body>
    <%= render 'layouts/topbar' %>
    <%#= render 'layouts/navigation' %>

    <div class="container-fluid main-container">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :overview %><br />
    <%= f.text_area :overview %>
  </div>
  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :identifier %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, Project.statuses_for_select %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>overview</th>
    <th>Identifier</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.overview %></td>
    <td><%= project.identifier %></td>
    <td><%= project.status %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>overview:</b>
  <%= @project.overview %>
</p>

<p>
  <b>Identifier:</b>
  <%= @project.identifier %>
</p>

<p>
  <b>Status cd:</b>
  <%= @project.status_cd %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/sites/_notice.html.erb
<div class="hero-unit">
  <button type="button" class="close hidden-phone" data-dismiss="alert">&times;</button>
  <h1>Welcome!</h1>
  <p>Hi guy! There is no project now. You need to create project and then create tasks for the project appointed. </p>
  <div class="pull-right">
    <%= link_to "New Project", new_admin_project_path, class: 'btn btn-primary' %>
    <%= link_to "New Task", new_admin_task_path, class: 'btn btn-info' %>
  </div>
</div>

app/views/sites/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <%= render 'tasks/sidebar' %>

    <div class="container-fluid content-wrapper">
      <div class="row-fluid">
        <div class="span12">
          <%= render 'sites/notice' if Project.count == 0 %>
          <div class="accordion" id="task-list">
            <% @tasks.order(:status_cd).group_by(&:status).each do |status, tasks| %>
              <h3><%= status.to_s.pluralize.capitalize %></h3>
              <%= render "tasks/listbox", tasks: tasks %>
            <% end -%>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span12">&nbsp;</div>
    </div>
  </div>
</div>

app/views/tasks/_listbox.html.erb
<div class="squiggly-border"></div>
<% tasks.each do |task| %>
  <div class="accordion-group priority-<%= task.priority %>">
    <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#task-list" href=<%= "#collapse-#{task.id}" %>>
        <i class="radmin-icon radmin-checkbox<%= "-unchecked" if task.todo? %>"></i>
        <%= "##{task.id} #{task.subject}" %>
        <% if @project.nil? %>
          <span class="label label-inverse"><%= task.project.name %></span>
        <% end -%>
        <span class="label label-<%= task.type %>"><%= task.type.capitalize %></span>
        <% if task.doing? %>
          <span class="label">Doing</span>
        <% end -%>
      </a>
    </div>
    <div id=<%= "collapse-#{task.id}" %> class="accordion-body collapse <%= "in" if task.id.to_s == params[:task_id] %>">
      <div class="accordion-inner">
        <% if task.assignee.present? %>
          <div class="info-inline">
            <b><%= task.todo? ? "Assignee To:" : "Finished by:" %></b>
            <%= task.assignee.nickname %>
          </div>
        <% end -%>
        <% if task.checker.present? %>
          <div class="info-inline">
            <b>Checked by:</b>
            <%= task.checker.nickname %>
          </div>
        <% end -%>
        <% if task.creater.present? %>
          <div class="info-inline">
            <b>Created by:</b>
            <%= task.creater.nickname %>
          </div>
        <% end -%>
        <div>
          <% unless task.description.blank? %>
            <b>Description:</b>
            <p><%= task.description.html_safe %></p>
          <% end -%>
        </div>
        <% unless task.done? %>
          <div class="btn-group">
            <% if task.todo? %>
              <% unless task.doing? %>
                <a href=<%= take_task_path(task) %> class="btn btn-small" data-method="post" rel="nofollow"><i class="icon-tag"></i> Take</a>
              <% end -%>
              <a href=<%= finish_task_path(task) %> class="btn btn-small" data-method="post" rel="nofollow"> <i class="icon-ok"></i> Finish</a>
              <a href=<%= edit_admin_task_path(task) %>><button class="btn btn-small"><i class="icon-pencil"></i> Edit</button></a>
              <%= link_to [:admin, task], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small"  do %>
                <i class="icon-remove"></i> Delete
              <% end -%>
            <% elsif task.toreview? %>
              <a href=<%= rollback_task_path(task) %> data-method="post" rel="nofollow" class="btn btn-small"><i class="icon-repeat"></i> Rollback</a>
              <a href=<%= checked_task_path(task) %> data-method="post" rel="nofollow" class="btn btn-small"><i class="icon-ok"></i> Checked</a>
            <% end -%>
          </div>
        <% end -%>
      </div>
    </div>
  </div>
<% end -%>

<!-- Modal Example
<a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>

<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>
-->

app/views/tasks/index.html.erb
<div class="row-fluid">
  <div class="span12">
    <%= render 'tasks/sidebar' %>

    <div class="container-fluid content-wrapper">
      <div class="row-fluid">
        <div class="span12">

          <ul class="breadcrumb">
            <li><a href=<%= root_path %>>Home</a> <span class="divider">/</span></li>
            <li><a href="javascript:void(0);"><%= @project.name %></a> <span class="divider">/</span></li>
            <li class="active">Tasks</li>
          </ul>

          <div class="accordion" id="task-list">
            <% @tasks.order(:status_cd).group_by(&:status).each do |status, tasks| %>
              <h3><%= status.to_s.pluralize.capitalize %></h3>
              <%= render "tasks/listbox", tasks: tasks %>
            <% end -%>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span12">&nbsp;</div>
    </div>
  </div>
</div>